---
- name: Setup Kubernetes prerequisites on EC2 instances
  hosts: aws_ec2
  become: yes

  tasks:
    - name: Load Kernel Modules for Containerd
      block:
        - name: Ensure required modules are loaded in containerd configuration
          ansible.builtin.blockinfile:
            path: /etc/modules-load.d/containerd.conf
            block: |
              overlay
              br_netfilter
            create: yes
            marker: "# {mark} ANSIBLE MANAGED MODULES"

        - name: Load overlay module
          community.general.modprobe:
            name: overlay
            state: present

        - name: Load br_netfilter module
          community.general.modprobe:
            name: br_netfilter
            state: present

    - name: Configure System Parameters for Kubernetes Networking
      block:
        - name: Configure iptables settings
          ansible.builtin.blockinfile:
            path: /etc/sysctl.d/kubernetes.conf
            block: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
            create: yes
            marker: "# {mark} ANSIBLE MANAGED MODULES"

        - name: Set sysctl parameters
          ansible.builtin.command:
            cmd: sysctl --system

    - name: Setup Docker Repository and Install Containerd
      block:
        - name: Create keyrings directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Add Docker Repository GPG Key
          ansible.builtin.shell: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          args:
            creates: /etc/apt/keyrings/docker.gpg

        - name: Add Docker Repository
          ansible.builtin.shell: |
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        - name: Update apt repository cache
          ansible.builtin.apt:
            update_cache: yes
            force_apt_get: yes

        - name: Install containerd
          ansible.builtin.apt:
            name: containerd.io

    - name: Configure and Start Containerd
      block:
        - name: Create containerd configuration directory
          ansible.builtin.file:
            path: /etc/containerd
            state: directory

        - name: Generate default containerd configuration
          ansible.builtin.command:
            cmd: "containerd config default > /etc/containerd/config.toml"
            creates: /etc/containerd/config.toml

        - name: Update SystemdCgroup setting in containerd config
          ansible.builtin.lineinfile:
            path: /etc/containerd/config.toml
            regexp: '^SystemdCgroup = false'
            line: 'SystemdCgroup = true'

        - name: Reload systemd daemon
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: Restart containerd service
          ansible.builtin.systemd:
            name: containerd
            state: restarted

        - name: Enable containerd service to start on boot
          ansible.builtin.systemd:
            name: containerd
            enabled: yes

    - name: Install Kubernetes Packages
      block:
        - name: Update apt repository cache
          ansible.builtin.apt:
            update_cache: yes
            force_apt_get: yes

        - name: Install apt-transport-https and other dependencies
          ansible.builtin.apt:
            name: 
              - apt-transport-https
              - ca-certificates
              - curl
            state: present

        - name: Add Kubernetes Repository GPG Key
          ansible.builtin.shell: |
            curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          args:
            creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

        - name: Add Kubernetes Repository
          ansible.builtin.shell: |
            echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /' > /etc/apt/sources.list.d/kubernetes.list
          args:
            creates: /etc/apt/sources.list.d/kubernetes.list

        - name: Update apt repository cache
          ansible.builtin.apt:
            update_cache: yes
            force_apt_get: yes

        - name: Install Kubernetes tools
          ansible.builtin.apt:
            name:
              - kubelet
              - kubeadm
              - kubectl
            state: present

        - name: Hold Kubernetes packages at current version
          ansible.builtin.command:
            cmd: apt-mark hold kubelet kubeadm kubectl

    - name: Enable kubelet Service
      ansible.builtin.systemd:
        name: kubelet
        enabled: true